name: hullah_app
description: "A dress tailoring consultation and recommendations app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-267.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  photo_view: ^0.14.0
  
  # Utilities
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  pdf: ^3.10.4
  flutter_svg: ^2.0.9
  http: ^1.1.0
  # Note: intl version is pinned by flutter_localizations, so we don't specify it
  
  # Navigation
  go_router: ^12.1.3
  
  # Form Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.1.2
  
  # Loading Indicators
  flutter_spinkit: ^5.2.0
  
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  flutter_launcher_icons: ^0.14.3
  flutter_pdfview: ^1.4.0+1
  printing: ^5.14.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700